import { Network } from "@aptos-labs/ts-sdk"

export const APTOS_NETWORK = Network.DEVNET
export const APTOS_NETWORK_NAME = "devnet"

export const REAL_NFT_MODULE_ADDRESS =
  "0xb61ff39ec3c625ff169d3de1859cb74a05238ff18bb6ee4a19cd10375a9dfda8"

export const REAL_NFT_MODULE_NAME = "RealNFT"
export const REAL_NFT_MINT_FUNCTION = `${REAL_NFT_MODULE_ADDRESS}::${REAL_NFT_MODULE_NAME}::mint`
export const REAL_NFT_STORE = `${REAL_NFT_MODULE_ADDRESS}::${REAL_NFT_MODULE_NAME}::NFTStore`

export const MARKETPLACE_MODULE_NAME = "Marketplace"
export const MARKETPLACE_STORE = `${REAL_NFT_MODULE_ADDRESS}::${MARKETPLACE_MODULE_NAME}::MarketplaceStore`
export const MARKETPLACE_INIT_FUNCTION = `${REAL_NFT_MODULE_ADDRESS}::${MARKETPLACE_MODULE_NAME}::init`
export const MARKETPLACE_LIST_FUNCTION = `${REAL_NFT_MODULE_ADDRESS}::${MARKETPLACE_MODULE_NAME}::list_nft`
export const MARKETPLACE_CANCEL_FUNCTION = `${REAL_NFT_MODULE_ADDRESS}::${MARKETPLACE_MODULE_NAME}::cancel_listing`
export const MARKETPLACE_BUY_FUNCTION = `${REAL_NFT_MODULE_ADDRESS}::${MARKETPLACE_MODULE_NAME}::buy_nft`

export const DEVNET_MARKETPLACE_ACCOUNTS = [
  REAL_NFT_MODULE_ADDRESS,
  "0xa27f621be56df24a0596d318bcef80662dc877240441a9d7d6f55a15a93bbc11",
  "0x643472a8b541b329721fc406fc47bc56b61041d129d3e71791d6a42103843166",
]
